
version: 2

models:
  - name: stg_airport
    description: "stage airport"
models:
  - name: stg_flight
    description: "stage airport"
models:
  - name: stg_carrier
    description: "stage airport"