select 
    code,
    DESCRIPTION, 
    META.AS_OF_DATE
from DEV_GLUNDE.RAW_FLUGMODELL.PSA_CARRIER as PSA
JOIN DEV_GLUNDE.RAW_FLUGMODELL.META_INTERFACE_RUN as META 
    ON PSA.INTERFACE_RUN_ID=META.INTERFACE_RUN_ID
where PSA.INTERFACE_RUN_ID = 2
